@extends('layouts.app')
@section('content')
@include('component.header')
@include('Konten.hiburan')
@include('auth.login')
@include('auth.register')
@endsection
@section('style')
@include('stylebody.styleHiburan')
@endsection